[package]
name = "rs"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "schnorrkelcbindings"
crate-type = ["cdylib", "staticlib"]

[dependencies]
schnorrkel = "^0.10"
hex = "^0.4"

[dev-dependencies]
hex-literal = "^0.3"
rand = "^0.8"

[build-dependencies]
cbindgen = "^0.24"
