name: Backend

on: [workflow_dispatch, push, pull_request]

jobs:
  run:
    uses: flarum/framework/.github/workflows/REUSABLE_backend.yml@main
    with:
      enable_backend_testing: true

      backend_directory: .
      php_versions: '["8.0", "8.1"]'
      php_extensions: 'curl, dom, gd, json, mbstring, openssl, pdo_mysql, tokenizer, zip, gmp, ffi'
      php_ini_values: error_reporting=E_ALL;ffi.enable=true
